import { z } from "zod";
export const isoDateTime=z.string().datetime({offset:true}); export const money=z.number().min(0); export const confidence=z.number().min(0).max(1); export const jsonObject=z.record(z.string(),z.unknown()); export const id=(p:string)=>z.string().regex(new RegExp(`^${p}_[A-Za-z0-9][A-Za-z0-9_-]*$`));
export const AuditAction=z.enum(["created","updated","review_requested","approval_granted","approval_revoked","rejected","blocked","qa_started","qa_passed","qa_failed","publish_attempted","publish_blocked","shopify_draft_created","printify_synced","webhook_received","job_claimed","job_completed","job_failed"]); export type AuditAction=z.infer<typeof AuditAction>;
export const blockedReason=z.enum(["human_approval_required","risk_review_failed","print_file_qa_failed","margin_check_failed","mockups_incomplete","content_review_required","variant_mapping_invalid","collection_missing","provider_disabled","auth_required","missing_asset","rate_limited","high_risk_phrase"]); export type BlockedReason=z.infer<typeof blockedReason>;
export const publishGatesSchema=z.object({human_approved:z.boolean(),risk_checks_passed:z.boolean(),print_file_qa_passed:z.boolean(),margin_checks_passed:z.boolean(),mockups_complete:z.boolean(),title_reviewed:z.boolean(),description_reviewed:z.boolean(),tags_reviewed:z.boolean(),printify_variants_valid:z.boolean(),shopify_collection_assigned:z.boolean()}); export type PublishGates=z.infer<typeof publishGatesSchema>;
const allowed=z.enum(["inspiration_only","data_reference"]); const status=z.string(); const base=(p:string)=>z.object({id:id(p),created_at:isoDateTime});
export const trendSourceSchema=base("tsrc").extend({name:z.string(),type:z.string(),allowed_use:allowed,requires_manual_import:z.boolean(),notes:z.string().nullable(),active:z.boolean()});
export const trendSignalSchema=base("tsig").extend({source_id:id("tsrc"),source_url:z.string().url().nullable(),captured_at:isoDateTime,keyword:z.string(),related_terms:z.array(z.string()),category:z.string(),region:z.string(),season:z.string().nullable(),confidence,allowed_use:allowed,status:z.enum(["new","reviewed","clustered","archived","rejected"]),cluster_id:id("tclus").nullable(),notes:z.string().nullable(),updated_at:isoDateTime});
export const trendClusterSchema=base("tclus").extend({name:z.string(),signal_ids:z.array(id("tsig")),keywords:z.array(z.string()),aesthetic_tags:z.array(z.string()),seasonality:z.array(z.string()),target_customer:z.string(),confidence,status:z.enum(["pending_approval","approved","generating","complete","archived"]),approved_for_generation:z.boolean(),approved_by:z.string().nullable(),approved_at:isoDateTime.nullable(),updated_at:isoDateTime});
export const trendClusterSignalSchema=base("tclsig").extend({cluster_id:id("tclus"),signal_id:id("tsig")});
export const phraseCandidateSchema=base("phrase").extend({cluster_id:id("tclus"),text:z.string(),generated_by:z.string(),generation_prompt_ref:z.string(),status:z.enum(["draft","risk_review_required","risk_cleared","approved","rejected","archived"]), trademark_review:z.object({required:z.boolean(),status:z.enum(["not_checked","pending","cleared","blocked"]),checked_by:z.string().nullable(),checked_at:isoDateTime.nullable(),notes:z.array(z.string())}),approved_for_design:z.boolean(),approved_by:z.string().nullable(),approved_at:isoDateTime.nullable(),updated_at:isoDateTime});
export const riskChecksSchema=z.object({trademark_risk:z.boolean(),celebrity_reference:z.boolean(),sports_team_reference:z.boolean(),brand_lookalike:z.boolean(),disney_ip_risk:z.boolean(),music_artist_reference:z.boolean(),tv_show_reference:z.boolean(),college_reference:z.boolean(),nfl_nba_reference:z.boolean(),profanity_flag:z.boolean(),competitor_copy_flag:z.boolean()});
export const riskReviewSchema=base("risk").extend({entity_type:z.string(),entity_id:z.string(),checks:riskChecksSchema,risk_score:confidence,status:z.enum(["pending","auto_flagged","cleared","blocked"]),reviewed_by:z.string().nullable(),reviewer_id:z.string().nullable(),reviewed_at:isoDateTime.nullable(),notes:z.string().nullable()});
export const designBriefSchema=base("brief").extend({phrase_id:id("phrase"),cluster_id:id("tclus"),collection:z.string(),product_targets:z.array(z.string()),style_direction:jsonObject,generation_prompt:z.string(),negative_prompt:z.string(),status:z.enum(["draft","pending_approval","approved","generating","complete","archived","rejected","failed"]),approved_for_generation:z.boolean(),approved_by:z.string().nullable(),approved_at:isoDateTime.nullable(),updated_at:isoDateTime});
export const generationJobSchema=base("genjob").extend({brief_id:id("brief"),provider:z.string(),model:z.string(),prompt:z.string(),negative_prompt:z.string(),parameters:jsonObject,status:z.enum(["queued","running","completed","failed","cancelled"]),retry_count:z.number().int().min(0),max_retries:z.number().int().min(0),output_asset_id:id("asset").nullable(),error:z.string().nullable(),queued_at:isoDateTime,started_at:isoDateTime.nullable(),completed_at:isoDateTime.nullable()});
export const designAssetSchema=base("asset").extend({job_id:id("genjob").nullable(),brief_id:id("brief"),asset_type:z.string(),storage_bucket:z.string(),file_path:z.string(),file_size_bytes:z.number().min(0),width:z.number().int().positive(),height:z.number().int().positive(),dpi:z.number().int().positive(),transparent_background:z.boolean(),generator:z.string(),model:z.string(),qa_status:z.enum(["pending","running","passed","failed","blocked","rejected"]),risk_status:z.enum(["pending","cleared","blocked"]),approved_for_mockup:z.boolean(),approved_by:z.string().nullable(),approved_at:isoDateTime.nullable(),updated_at:isoDateTime});
export const printFileQaSchema=base("qa").extend({asset_id:id("asset"),checks:jsonObject,status:z.enum(["pending","running","passed","failed","blocked"]),blocked_reasons:z.array(blockedReason),approved_for_product_draft:z.boolean(),reviewed_at:isoDateTime.nullable()});
export const mockupTemplateSchema=base("mtemplate").extend({name:z.string(),product_type:z.string(),printify_blueprint_id:z.string(),canvas:jsonObject,base_image_path:z.string(),color_variants:z.array(z.string()),active:z.boolean()});
export const mockupAssetSchema=base("mockup").extend({asset_id:id("asset"),template_id:id("mtemplate"),product_draft_id:id("draft").nullable(),color_variant:z.string(),storage_bucket:z.string(),file_path:z.string(),width:z.number().int().positive(),height:z.number().int().positive(),status:z.enum(["queued","generated","failed","approved","rejected"]),approved_for_product:z.boolean(),updated_at:isoDateTime});
export const productDraftSchema=base("draft").extend({brand:z.string(),title:z.string(),description:z.string(),product_type:z.string(),collection:z.string(),tags:z.array(z.string()),brief_id:id("brief"),asset_id:id("asset"),mockup_ids:z.array(id("mockup")),variant_ids:z.array(id("var")),shopify_status:z.enum(["not_published","draft","published","failed"]),printify_status:z.enum(["not_synced","draft","synced","failed"]),approval_status:z.enum(["pending","approved","rejected"]),status:z.enum(["draft","pending_approval","approved","publishing","published","archived","rejected","failed"]),approved_by:z.string().nullable(),approved_at:isoDateTime.nullable(),publish_review_id:id("pubrev").nullable(),updated_at:isoDateTime});
export const productVariantSchema=base("var").extend({product_draft_id:id("draft"),sku:z.string(),size:z.string(),color:z.string(),color_hex:z.string(),printify_variant_id:z.string(),printify_blueprint_id:z.string(),printify_print_provider_id:z.string(),cost:money,price:money,compare_at_price:money.nullable(),margin_dollars:z.number(),margin_percent:z.number(),margin_ok:z.boolean(),weight_oz:z.number(),active:z.boolean()});
export const priceMarginCheckSchema=base("margin").extend({product_draft_id:id("draft"),variant_id:id("var"),cost:money,price:money,shopify_fee_estimate:money,printify_shipping_estimate:money,platform_fee_estimate:money,net_revenue_estimate:z.number(),margin_percent:z.number(),minimum_margin_threshold:z.number(),margin_ok:z.boolean(),blocked:z.boolean()});
export const publishReviewSchema=base("pubrev").extend({product_draft_id:id("draft"),gates:publishGatesSchema,all_gates_passed:z.boolean(),shopify_publish_allowed:z.boolean(),printify_sync_allowed:z.boolean(),reviewed_by:z.string().nullable(),reviewed_at:isoDateTime.nullable(),notes:z.array(z.string()),updated_at:isoDateTime}).superRefine((v,c)=>{const all=Object.values(v.gates).every(Boolean); if(v.all_gates_passed!==all)c.addIssue({code:"custom",message:"all_gates_passed inconsistent"}); if((v.shopify_publish_allowed||v.printify_sync_allowed)&&!all)c.addIssue({code:"custom",message:"publish allowed cannot be true when any gate is false"});});
export const shopifyProductRefSchema=base("shopref").extend({product_draft_id:id("draft"),shopify_product_id:z.string(),shopify_handle:z.string(),shopify_status:status,shopify_published_at:isoDateTime.nullable(),shopify_collection_ids:z.array(z.string()),shopify_variant_ids:jsonObject,synced_at:isoDateTime,updated_at:isoDateTime});
export const printifyProductRefSchema=base("ptyref").extend({product_draft_id:id("draft"),printify_product_id:z.string(),printify_shop_id:z.string(),printify_blueprint_id:z.string(),printify_print_provider_id:z.string(),printify_status:status,printify_published:z.boolean(),printify_external_id:z.string().nullable(),synced_at:isoDateTime,updated_at:isoDateTime});
export const fulfillmentEventSchema=base("fulfil").extend({shopify_product_ref_id:id("shopref").nullable(),printify_product_ref_id:id("ptyref").nullable(),event_type:z.string(),shopify_order_id:z.string().nullable(),printify_order_id:z.string().nullable(),status:z.enum(["pending","in_production","shipped","delivered","cancelled","failed"]),line_items:z.array(jsonObject),shipped_at:isoDateTime.nullable(),tracking_number:z.string().nullable(),tracking_url:z.string().url().nullable(),carrier:z.string().nullable(),raw_webhook_payload_ref:z.string().nullable(),updated_at:isoDateTime});
export const auditEventSchema=base("audit").extend({entity_type:z.string(),entity_id:z.string(),action:AuditAction,actor_type:z.enum(["human","system","provider"]),actor_id:z.string(),before_state:z.string().nullable(),after_state:z.string().nullable(),notes:z.string().nullable()});
export type RiskReview=z.infer<typeof riskReviewSchema>; export type PublishReview=z.infer<typeof publishReviewSchema>; export type AuditEvent=z.infer<typeof auditEventSchema>;
export const allSchemas=[trendSourceSchema,trendSignalSchema,trendClusterSchema,trendClusterSignalSchema,phraseCandidateSchema,riskReviewSchema,designBriefSchema,generationJobSchema,designAssetSchema,printFileQaSchema,mockupTemplateSchema,mockupAssetSchema,productDraftSchema,productVariantSchema,priceMarginCheckSchema,publishReviewSchema,shopifyProductRefSchema,printifyProductRefSchema,fulfillmentEventSchema,auditEventSchema];
export type PublishGateEvaluation={allowed:boolean;shopifyAllowed:boolean;printifyAllowed:boolean;blockedReasons:BlockedReason[];inconsistent:boolean;notes:string[]}; const reasons:Record<keyof PublishGates,BlockedReason>={human_approved:"human_approval_required",risk_checks_passed:"risk_review_failed",print_file_qa_passed:"print_file_qa_failed",margin_checks_passed:"margin_check_failed",mockups_complete:"mockups_incomplete",title_reviewed:"content_review_required",description_reviewed:"content_review_required",tags_reviewed:"content_review_required",printify_variants_valid:"variant_mapping_invalid",shopify_collection_assigned:"collection_missing"};
export function evaluatePublishReviewGates(review:PublishReview):PublishGateEvaluation{const parsed=publishReviewSchema.safeParse(review); const blocked=Object.entries(review.gates).filter(([,v])=>!v).map(([k])=>reasons[k as keyof PublishGates]); const all=blocked.length===0; return {allowed:all&&parsed.success,shopifyAllowed:all&&parsed.success,printifyAllowed:all&&parsed.success,blockedReasons:[...new Set(blocked)],inconsistent:!parsed.success,notes:parsed.success?review.notes:parsed.error.issues.map(i=>i.message)}}
export function createBlockedPublishEvaluation(blockedReasons:BlockedReason[],notes:string[]=[]):PublishGateEvaluation{return{allowed:false,shopifyAllowed:false,printifyAllowed:false,blockedReasons,inconsistent:false,notes}}
export function assertPublishAllowedForShopify(r:PublishReview){if(!evaluatePublishReviewGates(r).shopifyAllowed)throw new Error("Shopify publish blocked")} export function assertPublishAllowedForPrintify(r:PublishReview){if(!evaluatePublishReviewGates(r).printifyAllowed)throw new Error("Printify sync blocked")}
const transitions:any={trend:{new:["reviewed","rejected"],reviewed:["clustered","rejected"],clustered:["archived"]},phrase:{draft:["risk_review_required"],risk_review_required:["risk_cleared","rejected"],risk_cleared:["approved","rejected"],approved:["archived"]},brief:{draft:["pending_approval"],pending_approval:["approved","rejected"],approved:["generating","archived"],generating:["complete","failed"],failed:["approved"]},generation_job:{queued:["running","cancelled"],running:["completed","failed"],failed:["queued","cancelled"]},product_draft:{draft:["pending_approval"],pending_approval:["approved","rejected"],approved:["publishing","archived"],publishing:["published","failed"],failed:["approved"]}}; export function canTransition(m:string,f:string,t:string){return transitions[m]?.[f]?.includes(t)??false} export function assertTransition(m:string,f:string,t:string){if(!canTransition(m,f,t))throw new Error(`Invalid ${m} transition ${f} -> ${t}`)}
export const now="2026-06-29T00:00:00Z"; export const fixtures={trendSource:{id:"tsrc_01",name:"Manual",type:"manual",allowed_use:"inspiration_only",requires_manual_import:true,notes:"No scraping",active:true,created_at:now},trendSignal:{id:"tsig_01",source_id:"tsrc_01",source_url:null,captured_at:now,keyword:"coastal cowgirl",related_terms:["beach rodeo"],category:"fashion_pod",region:"US",season:"summer",confidence:.7,allowed_use:"inspiration_only",status:"new",cluster_id:null,notes:null,created_at:now,updated_at:now},publishReviewBlocked:{id:"pubrev_01",product_draft_id:"draft_01",gates:{human_approved:false,risk_checks_passed:true,print_file_qa_passed:true,margin_checks_passed:true,mockups_complete:true,title_reviewed:false,description_reviewed:false,tags_reviewed:false,printify_variants_valid:true,shopify_collection_assigned:false},all_gates_passed:false,shopify_publish_allowed:false,printify_sync_allowed:false,reviewed_by:null,reviewed_at:null,notes:["Human approval pending."],created_at:now,updated_at:now} satisfies PublishReview}; export const invalidFixtures={badIdTrendSource:{...fixtures.trendSource,id:"bad_01"},badConfidenceTrendSignal:{...fixtures.trendSignal,confidence:2}};
