import { DataTable, EmptyState, ImageGenerationJobCard, MetricCard, PageHeader, ProviderStatusCard, StatusBadge, WorkflowStepHeader } from "@saltyfactory/ui";
import { getStudioLists } from "../data";
import { getWorkspaceProviderReadiness, isProviderReady, providerCredentialSourceLabel } from "../_provider-readiness";
import { PrivateImagePreview } from "../_components/PrivateImagePreview";
import { assetPreviewPath } from "../_private-preview-paths";
import { GenerationStudioClient } from "./GenerationStudioClient";

type RecommendedModel = { model: string; label: string };

function ownerLabel(value: unknown, fallback = "pending") {
  return String(value ?? fallback).replace(/_/g, " ");
}

export default async function Page() {
  const { jobs, assets, briefs } = await getStudioLists();
  const readiness = await getWorkspaceProviderReadiness();
  const resolvedProvider = readiness.providers.image_generation;
  const storage = readiness.providers.storage;
  const connected = isProviderReady(resolvedProvider);
  const localDemo = resolvedProvider.credentialSource === "local_demo";
  const recommendedModels = (resolvedProvider.providerMetadata?.recommendedModels ?? []) as RecommendedModel[];
  const model = String(resolvedProvider.providerMetadata?.model ?? "not selected");
  const providerStatus = connected ? "Connected" : localDemo ? "Local demo" : "Setup required";
  const providerTone = connected ? "success" : localDemo ? "info" : "warning";
  const providerDescription = connected
    ? `Provider: Hugging Face. Model: ${model}. Credential source: ${providerCredentialSourceLabel(resolvedProvider.credentialSource)}.`
    : localDemo
      ? resolvedProvider.safeMessage
      : resolvedProvider.safeMessage;

  return <>
    <PageHeader title="Image Generation Studio" description="Generate private source-art variants, derivative packages, and print-ready files from approved briefs.">
      <a className="btn btn-primary" href="/studio/briefs">Send Approved Brief</a>
      {!connected ? <a className="btn btn-secondary" href="/studio/onboarding/providers/image-generation">Configure image generation</a> : null}
    </PageHeader>
    <GenerationStudioClient initialBriefs={briefs as any[]} />
    <div className="layout-grid layout-grid-3"><MetricCard title="Queued jobs" value={String(jobs.filter((j:any)=>j.status==="queued").length)} /><MetricCard title="Running" value={String(jobs.filter((j:any)=>j.status==="running").length)} tone="info" /><MetricCard title="Failed" value={String(jobs.filter((j:any)=>j.status==="failed").length)} tone="danger" /></div>
    <div className="layout-grid layout-grid-2" style={{ marginTop: 18 }}>
      <section className="surface-card">
        <WorkflowStepHeader step="3" title="Image Generation Jobs" status={connected ? "connected" : localDemo ? "local demo" : "setup needed"} description="The worker must persist generated bytes into private storage and create design asset records before a job can complete." />
        {jobs.length ? <DataTable columns={["Job", "Status", "Provider", "Retries", "Output"]} rows={jobs.map((job:any)=>[
          job.id,
          <StatusBadge key="s" status={job.status ?? "queued"} />,
          job.provider ?? "provider pending",
          String(job.retry_count ?? job.retryCount ?? 0),
          job.output_asset_id ?? job.outputAssetId ?? "asset pending"
        ])} /> : <EmptyState title="No generation jobs" description="Jobs appear after an approved prompt is queued against a configured image provider." />}
      </section>
      <section className="surface-card">
        <ProviderStatusCard
          title="Image generation provider"
          status={providerStatus}
          tone={providerTone}
          description={providerDescription}
          actionHref={resolvedProvider.setupRoute}
          actionLabel="Configure image generation"
        />
        <div style={{ marginTop: 14 }}>
          <ProviderStatusCard
            title="Generated asset storage"
            status={isProviderReady(storage) ? "Ready" : "Storage setup needed"}
            tone={isProviderReady(storage) ? "success" : "warning"}
            description={storage.safeMessage}
            actionHref={storage.setupRoute}
            actionLabel="Open storage setup"
          />
        </div>
        {connected ? <div className="action-bar" style={{ marginTop: 14 }}>
          <a className="btn btn-primary" href="/studio/briefs">Send approved brief</a>
          <a className="btn btn-secondary" href="/studio/onboarding/providers/image-generation">Review provider setup</a>
        </div> : null}
        {!connected ? <div style={{ marginTop: 14 }}>
          <h2>Recommended models</h2>
          <ul>
            {recommendedModels.map((item) => <li key={item.model}><strong>{item.label}</strong> <code>{item.model}</code></li>)}
          </ul>
        </div> : null}
        <details className="setup-advanced-details">
          <summary>Advanced server fallback details</summary>
          <p>Guided Setup credentials take precedence. Developer-only fallback names and deployment notes live in Setup advanced details.</p>
          <a className="btn btn-secondary" href="/studio/setup">Open Setup advanced details</a>
        </details>
      </section>
    </div>
    {jobs.length ? <div className="layout-grid layout-grid-3" style={{ marginTop: 18 }}>
      {jobs.slice(0, 6).map((job: any) => <ImageGenerationJobCard key={job.id} title={job.title ?? job.id} status={job.status ?? "queued"} prompt={job.prompt ?? job.prompt_text ?? "Prompt stored in private job metadata."} />)}
    </div> : null}
    <section className="surface-card" style={{ marginTop: 18 }}>
      <h2>Generated Artwork</h2>
      {assets.length ? <div className="layout-grid layout-grid-3">{assets.slice(0, 9).map((asset: any) => {
        const approved = Boolean(asset.approved_for_mockup || asset.approvedForMockup);
        return <article key={asset.id} className="surface-card" style={{ display: "grid", gap: 10 }}>
          <PrivateImagePreview src={assetPreviewPath(asset)} alt="Generated private artwork preview" />
          <strong>{asset.id}</strong>
          <dl className="result-detail-grid">
            <div><dt>Provider</dt><dd>{asset.generator === "huggingface" ? "Hugging Face" : ownerLabel(asset.generator, "manual")}</dd></div>
            <div><dt>Model</dt><dd>{asset.model ?? model}</dd></div>
            <div><dt>QA</dt><dd>{ownerLabel(asset.qa_status ?? asset.qaStatus)}</dd></div>
            <div><dt>Created</dt><dd>{asset.created_at || asset.createdAt ? new Date(String(asset.created_at ?? asset.createdAt)).toLocaleDateString() : "saved"}</dd></div>
          </dl>
          <div className="action-bar">
            <a className="btn btn-primary" href={`/studio/assets?asset_id=${encodeURIComponent(String(asset.id))}`}>Open asset</a>
            {approved ? <a className="btn btn-secondary" href={`/studio/mockups?asset_id=${encodeURIComponent(String(asset.id))}`}>Create mockup</a> : <a className="btn btn-secondary" href={`/studio/assets?asset_id=${encodeURIComponent(String(asset.id))}`}>Review QA</a>}
          </div>
        </article>;
      })}</div> : <EmptyState title="No generated artwork yet" description="Send an approved brief to generation and the resulting private asset preview appears here." action={<a className="btn btn-primary" href="/studio/briefs">Open briefs</a>} />}
    </section>
  </>;
}
