import { DataTable, EmptyState, ImageGenerationJobCard, MetricCard, PageHeader, ProviderStatusCard, StatusBadge, WorkflowStepHeader } from "@saltyfactory/ui";
import { getStudioLists } from "../data";
import { getWorkspaceProviderReadiness, isProviderReady, providerCredentialSourceLabel } from "../_provider-readiness";

type RecommendedModel = { model: string; label: string };

export default async function Page() {
  const { jobs } = await getStudioLists();
  const readiness = await getWorkspaceProviderReadiness();
  const resolvedProvider = readiness.providers.image_generation;
  const storage = readiness.providers.storage;
  const connected = isProviderReady(resolvedProvider);
  const localDemo = resolvedProvider.credentialSource === "local_demo";
  const recommendedModels = (resolvedProvider.providerMetadata?.recommendedModels ?? []) as RecommendedModel[];
  const model = String(resolvedProvider.providerMetadata?.model ?? "not selected");
  const providerStatus = connected ? "Connected" : localDemo ? "Local demo" : "Setup required";
  const providerTone = connected ? "success" : localDemo ? "info" : "warning";
  const providerDescription = connected
    ? `Provider: Hugging Face. Model: ${model}. Credential source: ${providerCredentialSourceLabel(resolvedProvider.credentialSource)}.`
    : localDemo
      ? resolvedProvider.safeMessage
      : resolvedProvider.safeMessage;

  return <>
    <PageHeader title="Generation Queue" description="Provider-gated job monitoring for image generation and downstream asset processing.">
      <a className="btn btn-primary" href="/studio/briefs">Send Approved Brief</a>
      {!connected ? <a className="btn btn-secondary" href="/studio/onboarding/providers/image-generation">Configure image generation</a> : null}
    </PageHeader>
    <div className="layout-grid layout-grid-3"><MetricCard title="Queued jobs" value={String(jobs.filter((j:any)=>j.status==="queued").length)} /><MetricCard title="Running" value={String(jobs.filter((j:any)=>j.status==="running").length)} tone="info" /><MetricCard title="Failed" value={String(jobs.filter((j:any)=>j.status==="failed").length)} tone="danger" /></div>
    <div className="layout-grid layout-grid-2" style={{ marginTop: 18 }}>
      <section className="surface-card">
        <WorkflowStepHeader step="3" title="Image Generation Jobs" status={connected ? "connected" : localDemo ? "local demo" : "setup needed"} description="The worker must persist generated bytes into private storage and create design asset records before a job can complete." />
        {jobs.length ? <DataTable columns={["Job", "Status", "Provider", "Retries", "Output"]} rows={jobs.map((job:any)=>[
          job.id,
          <StatusBadge key="s" status={job.status ?? "queued"} />,
          job.provider ?? "provider pending",
          String(job.retry_count ?? job.retryCount ?? 0),
          job.output_asset_id ?? job.outputAssetId ?? "asset pending"
        ])} /> : <EmptyState title="No generation jobs" description="Jobs appear after an approved prompt is queued against a configured image provider." />}
      </section>
      <section className="surface-card">
        <ProviderStatusCard
          title="Image generation provider"
          status={providerStatus}
          tone={providerTone}
          description={providerDescription}
          actionHref={resolvedProvider.setupRoute}
          actionLabel="Configure image generation"
        />
        <div style={{ marginTop: 14 }}>
          <ProviderStatusCard
            title="Generated asset storage"
            status={isProviderReady(storage) ? "Ready" : "Storage setup needed"}
            tone={isProviderReady(storage) ? "success" : "warning"}
            description={storage.safeMessage}
            actionHref={storage.setupRoute}
            actionLabel="Open storage setup"
          />
        </div>
        {connected ? <div className="action-bar" style={{ marginTop: 14 }}>
          <a className="btn btn-primary" href="/studio/briefs">Send approved brief</a>
          <a className="btn btn-secondary" href="/studio/onboarding/providers/image-generation">Review provider setup</a>
        </div> : null}
        {!connected ? <div style={{ marginTop: 14 }}>
          <h2>Recommended models</h2>
          <ul>
            {recommendedModels.map((item) => <li key={item.model}><strong>{item.label}</strong> <code>{item.model}</code></li>)}
          </ul>
        </div> : null}
        <details className="setup-advanced-details">
          <summary>Advanced server fallback details</summary>
          <p>Guided Setup credentials take precedence. Developer-only fallback names and deployment notes live in Setup advanced details.</p>
          <a className="btn btn-secondary" href="/studio/setup">Open Setup advanced details</a>
        </details>
      </section>
    </div>
    {jobs.length ? <div className="layout-grid layout-grid-3" style={{ marginTop: 18 }}>
      {jobs.slice(0, 6).map((job: any) => <ImageGenerationJobCard key={job.id} title={job.title ?? job.id} status={job.status ?? "queued"} prompt={job.prompt ?? job.prompt_text ?? "Prompt stored in private job metadata."} />)}
    </div> : null}
  </>;
}
