import { publicImageGenerationProviderResolution, resolveImageGenerationProvider } from "@saltyfactory/ai-free";
import { parseEnv } from "@saltyfactory/config";
import { createRepositories, type RepositoryBundle } from "@saltyfactory/db";
import { AdvancedConfigDetails, DataTable, EmptyState, ImageGenerationJobCard, MetricCard, PageHeader, ProviderStatusCard, StatusBadge, WorkflowStepHeader } from "@saltyfactory/ui";
import { getStudioLists } from "../data";
import { studioWorkspaceId } from "../../api/studio/design-suggestions/_shared";

function canOpenRepositories() {
  return process.env.NODE_ENV === "test" || process.env.REPOSITORY_ADAPTER === "memory" || Boolean(process.env.DATABASE_URL) || process.env.APP_ENV === "production";
}

function openRepositoriesSafely(): RepositoryBundle | undefined {
  if (!canOpenRepositories()) return undefined;
  try {
    return createRepositories();
  } catch {
    return undefined;
  }
}

function credentialSourceLabel(source: string) {
  if (source === "credential_store") return "secure workspace credential";
  if (source === "env") return "advanced server fallback";
  if (source === "local_demo") return "local demo mode";
  return "not connected";
}

export default async function Page() {
  const { jobs } = await getStudioLists();
  const cfg = parseEnv();
  const repos = openRepositoriesSafely();
  const resolvedProvider = publicImageGenerationProviderResolution(await resolveImageGenerationProvider({ workspaceId: studioWorkspaceId, repos, config: cfg }));
  const connected = resolvedProvider.status === "ready";
  const localDemo = resolvedProvider.status === "local_demo";
  const providerStatus = connected ? "Connected" : localDemo ? "Local demo" : "Setup required";
  const providerTone = connected ? "success" : localDemo ? "info" : "warning";
  const providerDescription = connected
    ? `Provider: Hugging Face. Model: ${resolvedProvider.model ?? "not selected"}. Credential source: ${credentialSourceLabel(resolvedProvider.credentialSource)}.`
    : localDemo
      ? resolvedProvider.safeMessage
      : resolvedProvider.safeMessage;

  return <>
    <PageHeader title="Generation Queue" description="Provider-gated job monitoring for image generation and downstream asset processing.">
      <a className="btn btn-primary" href="/studio/briefs">Send Approved Brief</a>
      {!connected ? <a className="btn btn-secondary" href="/studio/onboarding/providers/image-generation">Configure image generation</a> : null}
    </PageHeader>
    <div className="layout-grid layout-grid-3"><MetricCard title="Queued jobs" value={String(jobs.filter((j:any)=>j.status==="queued").length)} /><MetricCard title="Running" value={String(jobs.filter((j:any)=>j.status==="running").length)} tone="info" /><MetricCard title="Failed" value={String(jobs.filter((j:any)=>j.status==="failed").length)} tone="danger" /></div>
    <div className="layout-grid layout-grid-2" style={{ marginTop: 18 }}>
      <section className="surface-card">
        <WorkflowStepHeader step="3" title="Image Generation Jobs" status={connected ? "connected" : localDemo ? "local demo" : "setup needed"} description="The worker must persist generated bytes into private storage and create design asset records before a job can complete." />
        {jobs.length ? <DataTable columns={["Job", "Status", "Provider", "Retries", "Output"]} rows={jobs.map((job:any)=>[
          job.id,
          <StatusBadge key="s" status={job.status ?? "queued"} />,
          job.provider ?? "provider pending",
          String(job.retry_count ?? job.retryCount ?? 0),
          job.output_asset_id ?? job.outputAssetId ?? "asset pending"
        ])} /> : <EmptyState title="No generation jobs" description="Jobs appear after an approved prompt is queued against a configured image provider." />}
      </section>
      <section className="surface-card">
        <ProviderStatusCard
          title="Image generation provider"
          status={providerStatus}
          tone={providerTone}
          description={providerDescription}
          actionHref={resolvedProvider.setupAction}
          actionLabel="Configure image generation"
        />
        {connected ? <div className="action-bar" style={{ marginTop: 14 }}>
          <a className="btn btn-primary" href="/studio/briefs">Send approved brief</a>
          <a className="btn btn-secondary" href="/studio/onboarding/providers/image-generation">Review provider setup</a>
        </div> : null}
        {!connected ? <div style={{ marginTop: 14 }}>
          <h2>Recommended models</h2>
          <ul>
            {resolvedProvider.recommendedModels.map((item) => <li key={item.model}><strong>{item.label}</strong> <code>{item.model}</code></li>)}
          </ul>
        </div> : null}
        <AdvancedConfigDetails
          envVars={["AI_IMAGE_ENABLED", "HF_API_TOKEN", "HF_IMAGE_MODEL", "IMAGE_GENERATION_ENABLED", "IMAGE_GENERATION_PROVIDER", "LOCAL_DEV_IMAGE_GENERATION"]}
          notes={[
            "Guided Setup credentials take precedence over advanced server fallback variables.",
            "Use local demo mode only in development/test.",
            "No OpenAI or Anthropic image provider is used."
          ]}
        />
      </section>
    </div>
    {jobs.length ? <div className="layout-grid layout-grid-3" style={{ marginTop: 18 }}>
      {jobs.slice(0, 6).map((job: any) => <ImageGenerationJobCard key={job.id} title={job.title ?? job.id} status={job.status ?? "queued"} prompt={job.prompt ?? job.prompt_text ?? "Prompt stored in private job metadata."} />)}
    </div> : null}
  </>;
}
